
import React, { createContext, useState, useContext, useEffect, ReactNode } from 'react';

type Language = 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'rtl' | 'ltr';
}

const translations = {
  ar: {
    // Main App & Login
    'app_name': 'نظام إدارة مجموعة EB',
    'login_title': 'نظام إدارة مجموعة EB',
    'login_subtitle': 'الإصدار 4.0',
    'username': 'اسم المستخدم',
    'password': 'كلمة المرور',
    'login_button': 'دخول للنظام',
    'copyright': 'جميع الحقوق محفوظة للمهندس شريف رشاد © 2026',
    
    // General Actions
    'save': 'حفظ البيانات',
    'cancel': 'إلغاء',
    'delete': 'حذف',
    'edit': 'تعديل',
    'add': 'إضافة جديد',
    'search': 'بحث سريع...',
    'print': 'طباعة المستند',
    'back': 'رجوع',
    'loading': 'جاري التحميل...',
    'status': 'الحالة',
    'date': 'التاريخ',
    'total': 'الإجمالي',
    'actions': 'الإجراءات',
    'description': 'الوصف / البيان',
    'documents': 'المستندات والمرفقات',
    'upload_document': 'رفع مستند جديد',
    'document_name': 'اسم المستند',
    'no_documents': 'لا توجد مستندات مرفقة',
    'view_file': 'عرض الملف',
    'images': 'الصور المرفقة',
    'upload_images': 'رفع من الجهاز',
    'use_camera': 'تصوير بالكاميرا',

    // Sidebar
    'dashboard': 'لوحة التحكم',
    'clients': 'العملاء',
    'price_offers': 'عروض الأسعار',
    'invoices': 'الفواتير الضريبية',
    'hr_management': 'شؤون الموظفين',
    'daily_reports': 'التقارير اليومية',
    'finance': 'الإدارة المالية',
    'companies': 'الشركات التابعة',
    'projects_management': 'إدارة المشاريع',
    'correspondence_system': 'نظام المخاطبات',
    'profile': 'الملف الشخصي',
    'logout': 'تسجيل الخروج',
    'navigation': 'القائمة الرئيسية',

    // Correspondence
    'correspondence': 'المخاطبات',
    'incoming': 'البريد الوارد',
    'outgoing': 'البريد الصادر',
    'ref_no': 'رقم المرجع',
    'subject': 'الموضوع',
    'sender': 'الجهة المرسلة',
    'recipient_to': 'الجهة المرسل إليها',
    'content': 'نص الخطاب',
    'add_correspondence': 'إضافة خطاب جديد',
    'click_to_upload': 'اضغط لرفع المرفقات',
    'attachments': 'المرفقات',
    'project_manager': 'مدير المشروع',
    'general_correspondence': 'مخاطبات عامة',

    // Finance & Invoices
    'financial_position': 'المركز المالي',
    'payment_orders': 'أوامر الصرف',
    'new_payment_order': 'أمر صرف جديد',
    'vouchers': 'السندات المالية',
    'receipt_voucher': 'سند قبض',
    'payment_voucher': 'سند صرف',
    'employee_custody': 'العهد المالية',
    'suppliers_contractors': 'الموردين والمقاولين',
    'bank_accounts': 'الحسابات البنكية',
    'add_bank_account': 'إضافة حساب بنكي',
    'add_supplier': 'إضافة مورد/مقاول',
    'supplier_name': 'اسم المورد/المقاول',
    'supplier_type': 'التصنيف',
    'type_supplier': 'مورد',
    'type_contractor': 'مقاول باطن',
    'service_product': 'الخدمة / المنتج',
    'bank_name': 'اسم البنك',
    'select_bank': '-- اختر البنك --',
    'account_name': 'اسم الحساب',
    'iban': 'رقم الآيبان (IBAN)',
    'current_balance': 'الرصيد الحالي',
    'revenues': 'إجمالي الإيرادات',
    'expenses': 'إجمالي المصروفات',
    'bank_cash': 'النقدية والبنوك',
    'create_invoice': 'إصدار فاتورة ضريبية',
    'invoice_number': 'رقم الفاتورة',
    'project': 'المشروع المرتبط',
    'select_project': '-- اختر المشروع --',
    'select_item': '-- اختر بند العمل --',
    'item_budget_status': 'حالة ميزانية البند',
    'budget_amount': 'الميزانية التقديرية',
    'spent_amount': 'المصروف سابقاً',
    'remaining_budget': 'المتبقي من التكلفة',
    'vat_15': 'ضريبة القيمة المضافة (15%)',
    'total_with_vat': 'الإجمالي شامل الضريبة',
    'subtotal': 'المجموع الفرعي',
    'amount': 'المبلغ',
    'payment_method': 'طريقة الدفع',
    'recipient_name': 'اسم المستفيد',

    // Projects
    'add_project': 'إضافة مشروع جديد',
    'project_name': 'اسم المشروع',
    'contract_value': 'قيمة العقد',
    'start_date': 'تاريخ البدء',
    'end_date': 'تاريخ الانتهاء',
    'active_projects': 'المشاريع النشطة',
    'total_contracts': 'إجمالي قيمة العقود',
    'work_items': 'بنود الأعمال',
    'payment_schedule': 'جدول الدفعات',
    'project_documents': 'وثائق ومخططات المشروع',
    'time_schedule': 'البرنامج الزمني (Gantt)',
    'doc_category': 'نوع الملف',
    'cat_CONTRACT': 'عقود',
    'cat_PLAN': 'مخططات عامة',
    'cat_LETTER': 'خطابات وأوراق',
    'cat_OTHER': 'أخرى',
    'cat_ARCHITECTURAL': 'مخططات معمارية',
    'cat_STRUCTURAL': 'مخططات إنشائية',
    'cat_MECHANICAL': 'مخططات ميكانيكية',
    'cat_ELECTRICAL': 'مخططات كهربائية',
    'cat_INTERIOR': 'تصميم داخلي',
    'cat_EXTERIOR': 'تصميم خارجي',

    // Clients
    'client_list': 'قائمة العملاء',
    'add_new_client': 'إضافة عميل جديد',
    'client_name': 'اسم العميل',
    'phone_number': 'رقم الهاتف',
    'email': 'البريد الإلكتروني',
    'national_id': 'رقم الهوية / السجل',
    'license_number': 'رقم الرخصة',
    'id_image': 'صورة الهوية',
    'license_image': 'صورة الرخصة',
    'client_documents': 'مستندات العميل',

    // HR & Employee Levels
    'employee_directory': 'دليل الموظفين',
    'add_new_employee': 'إضافة موظف',
    'job_title': 'المسمى الوظيفي',
    'department': 'القسم',
    'salary': 'الراتب',
    'loan_balance': 'رصيد السلف',
    'vacation_balance': 'رصيد الإجازات',
    'id_expiry': 'انتهاء الهوية',
    'register_employee': 'تسجيل موظف جديد',
    'job_level': 'المستوى الوظيفي',
    'role_group_manager': 'مدير المجموعة',
    'role_company_manager': 'مدير شركة',
    'role_dept_manager': 'مدير قسم',
    'role_engineer': 'مهندس',
    'role_supervisor': 'مشرف',
    'role_employee': 'موظف',
    'role_technician': 'فني',
    'manage_employees_permissions': 'إدارة الموظفين والصلاحيات',
    'personal_data': 'البيانات الشخصية',
    'job_data': 'البيانات الوظيفية',
    'detailed_permissions': 'الصلاحيات التفصيلية',
    'upload_photo': 'رفع صورة شخصية',
    'save_employee': 'حفظ بيانات الموظف',
    'edit_employee': 'تعديل بيانات الموظف',
    'notifications_tasks': 'الإشعارات والمهام',
    'write_task': 'اكتب مهمة أو إشعار...',
    'send': 'إرسال',
    'no_notifications': 'لا توجد إشعارات حالياً',
    'perm_VIEW_DASHBOARD': 'عرض لوحة التحكم',
    'perm_VIEW_CLIENTS': 'عرض العملاء',
    'perm_MANAGE_CLIENTS': 'إدارة العملاء',
    'perm_SEND_EMAILS': 'إرسال إيميلات',
    'perm_VIEW_PROJECTS': 'عرض المشاريع',
    'perm_MANAGE_PROJECTS': 'إدارة المشاريع',
    'perm_DELETE_PROJECTS': 'حذف المشاريع',
    'perm_VIEW_REPORTS': 'عرض التقارير',
    'perm_ADD_REPORT': 'إضافة تقرير',
    'perm_PRINT_REPORT': 'طباعة التقارير',
    'perm_SHARE_WHATSAPP': 'مشاركة واتساب',
    'perm_MANAGE_REPORTS': 'إدارة التقارير',
    'perm_VIEW_FINANCE': 'عرض المالية',
    'perm_ADD_PAYMENT_ORDER': 'إضافة أمر صرف',
    'perm_MANAGE_FINANCE': 'إدارة المالية',
    'perm_VIEW_EMPLOYEES': 'عرض الموظفين',
    'perm_MANAGE_EMPLOYEES': 'إدارة الموظفين',
    'perm_VIEW_SALARIES': 'عرض الرواتب',
    'perm_MANAGE_CONTRACTS': 'إدارة العقود',
    'insurance_expiry': 'انتهاء التأمين',
    'contract_expiry': 'انتهاء العقد',
    'full_name': 'الاسم الكامل',
    'employee_docs': 'وثائق الموظفين',
    'payroll_system': 'نظام الرواتب',
    'payroll_msg': 'نظام مسير الرواتب قيد التطوير...',
    'loans': 'السلف',
    'id_residence': 'رقم الهوية/الإقامة',
    'job_code': 'الكود الوظيفي',
    'permissions_count': 'عدد الصلاحيات',
    'permission': 'الصلاحية',
    'level_admin': 'إدارة عليا (Admin)',
    'level_manager': 'مدير شركة',
    'level_employee': 'موظف',
    'edit_company_data': 'تعديل بيانات الشركة',
    'full_name_company': 'اسم الشركة بالكامل',
    'commercial_register': 'السجل التجاري',
    'tax_number': 'الرقم الضريبي',
    'company_phone': 'هاتف الشركة',
    'po_box': 'صندوق البريد',
    'address': 'العنوان',
    'save_changes': 'حفظ التغييرات',
    'daily_work_report': 'تقرير العمل اليومي',
    'item_work': 'بند العمل',
    'progress_percent': 'نسبة الإنجاز',
    'notes': 'ملاحظات',
    'general_notes': 'ملاحظات عامة',
    'new_report': 'تقرير جديد',
    'select': 'اختر',
    'items_count': 'بند',
    'collected_amount': 'المحصل',
    'remaining_amount': 'المتبقي',
    'collection_rate': 'نسبة التحصيل',
    'payment_name': 'اسم الدفعة',
    'due_date': 'تاريخ الاستحقاق',
    'confirm_delete_client': 'هل أنت متأكد من حذف العميل',
    'confirm_delete_employee': 'هل أنت متأكد من حذف الموظف',
    'fill_client_name_phone': 'يرجى إدخال اسم العميل ورقم الهاتف',
    'edit_client_data': 'تعديل بيانات العميل',
    'total_contracts_value': 'إجمالي العقود',
    'collection_followup': 'متابعة التحصيل',
    'ai_analysis': 'تحليل الذكاء الاصطناعي',
    'no_clients': 'لا يوجد عملاء مسجلين',
    'fill_required': 'يرجى تعبئة الحقول المطلوبة',
    'fill_basic_fields': 'يرجى تعبئة البيانات الأساسية',
    'password_mismatch': 'كلمات المرور غير متطابقة',
    'password_changed': 'تم تغيير كلمة المرور بنجاح',
    'incorrect_current_password': 'كلمة المرور الحالية غير صحيحة',
    'change_password': 'تغيير كلمة المرور',
    'current_password': 'كلمة المرور الحالية',
    'new_password': 'كلمة المرور الجديدة',
    'confirm_password': 'تأكيد كلمة المرور',
    'recent_notifications': 'آخر الإشعارات',
    'assigned_company': 'الشركة التابعة',
    'days': 'يوم',
    'invoices_management': 'إدارة الفواتير',
    'invoice_date': 'تاريخ الفاتورة',
    'offer_code': 'رقم العرض',
    'grand_total': 'الإجمالي النهائي',
    'offer_notes_placeholder': 'شروط وأحكام العرض...',
    'create_offer': 'إنشاء عرض سعر',
    'none': 'لا يوجد',
    'valid_until': 'ساري حتى',
    'item_description': 'وصف البند',
    'unit': 'الوحدة',
    'quantity': 'الكمية',
    'unit_price': 'سعر الوحدة',
    'select_client': 'اختر العميل',
  },
  en: {
    'app_name': 'EB Group Management System',
    'login_title': 'EB Group Management System',
    'login_subtitle': 'Version 4.0',
    'username': 'Username',
    'password': 'Password',
    'login_button': 'Login',
    'copyright': 'All rights reserved © 2026',
    'save': 'Save',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'edit': 'Edit',
    'add': 'Add New',
    'search': 'Search...',
    'print': 'Print',
    'back': 'Back',
    'loading': 'Loading...',
    'status': 'Status',
    'date': 'Date',
    'total': 'Total',
    'actions': 'Actions',
    'description': 'Description',
    'documents': 'Documents',
    'upload_document': 'Upload Document',
    'document_name': 'Document Name',
    'no_documents': 'No documents attached',
    'view_file': 'View File',
    'images': 'Images',
    'upload_images': 'Upload Images',
    'use_camera': 'Use Camera',
    'dashboard': 'Dashboard',
    'clients': 'Clients',
    'price_offers': 'Price Offers',
    'invoices': 'Invoices',
    'hr_management': 'HR Management',
    'daily_reports': 'Daily Reports',
    'finance': 'Finance',
    'companies': 'Companies',
    'projects_management': 'Projects Management',
    'correspondence_system': 'Correspondence System',
    'profile': 'Profile',
    'logout': 'Logout',
    'navigation': 'Navigation',
    'correspondence': 'Correspondence',
    'incoming': 'Incoming',
    'outgoing': 'Outgoing',
    'ref_no': 'Ref No.',
    'subject': 'Subject',
    'sender': 'Sender',
    'recipient_to': 'Recipient',
    'content': 'Content',
    'add_correspondence': 'Add Correspondence',
    'click_to_upload': 'Click to upload',
    'attachments': 'Attachments',
    'project_manager': 'Project Manager',
    'general_correspondence': 'General Correspondence',
    'financial_position': 'Financial Position',
    'payment_orders': 'Payment Orders',
    'new_payment_order': 'New Payment Order',
    'vouchers': 'Vouchers',
    'receipt_voucher': 'Receipt Voucher',
    'payment_voucher': 'Payment Voucher',
    'employee_custody': 'Custody',
    'suppliers_contractors': 'Suppliers & Contractors',
    'bank_accounts': 'Bank Accounts',
    'add_bank_account': 'Add Bank Account',
    'add_supplier': 'Add Supplier/Contractor',
    'supplier_name': 'Supplier Name',
    'supplier_type': 'Type',
    'type_supplier': 'Supplier',
    'type_contractor': 'Sub-Contractor',
    'service_product': 'Service / Product',
    'bank_name': 'Bank Name',
    'select_bank': 'Select Bank',
    'account_name': 'Account Name',
    'iban': 'IBAN',
    'current_balance': 'Current Balance',
    'revenues': 'Revenues',
    'expenses': 'Expenses',
    'bank_cash': 'Cash & Banks',
    'create_invoice': 'Create Invoice',
    'invoice_number': 'Invoice No',
    'project': 'Project',
    'select_project': 'Select Project',
    'select_item': 'Select Item',
    'item_budget_status': 'Item Budget Status',
    'budget_amount': 'Budget Amount',
    'spent_amount': 'Spent Amount',
    'remaining_budget': 'Remaining Budget',
    'vat_15': 'VAT (15%)',
    'total_with_vat': 'Total with VAT',
    'subtotal': 'Subtotal',
    'amount': 'Amount',
    'payment_method': 'Payment Method',
    'recipient_name': 'Recipient Name',
    'add_project': 'Add Project',
    'project_name': 'Project Name',
    'contract_value': 'Contract Value',
    'start_date': 'Start Date',
    'end_date': 'End Date',
    'active_projects': 'Active Projects',
    'total_contracts': 'Total Contracts',
    'work_items': 'Work Items',
    'payment_schedule': 'Payment Schedule',
    'project_documents': 'Project Documents & Plans',
    'time_schedule': 'Time Schedule',
    'doc_category': 'Doc Category',
    'cat_CONTRACT': 'Contracts',
    'cat_PLAN': 'Plans',
    'cat_LETTER': 'Letters',
    'cat_OTHER': 'Other',
    'cat_ARCHITECTURAL': 'Architectural Plans',
    'cat_STRUCTURAL': 'Structural Plans',
    'cat_MECHANICAL': 'Mechanical Plans',
    'cat_ELECTRICAL': 'Electrical Plans',
    'cat_INTERIOR': 'Interior Design',
    'cat_EXTERIOR': 'Exterior Design',
    'client_list': 'Client List',
    'add_new_client': 'Add New Client',
    'client_name': 'Client Name',
    'phone_number': 'Phone Number',
    'email': 'Email',
    'national_id': 'National ID / CR',
    'license_number': 'License Number',
    'id_image': 'ID Image',
    'license_image': 'License Image',
    'client_documents': 'Client Documents',
    'employee_directory': 'Employee Directory',
    'add_new_employee': 'Add Employee',
    'job_title': 'Job Title',
    'department': 'Department',
    'salary': 'Salary',
    'loan_balance': 'Loan Balance',
    'vacation_balance': 'Vacation Balance',
    'id_expiry': 'ID Expiry',
    'register_employee': 'Register Employee',
    'job_level': 'Job Level',
    'role_group_manager': 'Group Manager',
    'role_company_manager': 'Company Manager',
    'role_dept_manager': 'Department Manager',
    'role_engineer': 'Engineer',
    'role_supervisor': 'Supervisor',
    'role_employee': 'Employee',
    'role_technician': 'Technician',
    'manage_employees_permissions': 'Manage Employees & Permissions',
    'personal_data': 'Personal Data',
    'job_data': 'Job Data',
    'detailed_permissions': 'Detailed Permissions',
    'upload_photo': 'Upload Photo',
    'save_employee': 'Save Employee',
    'edit_employee': 'Edit Employee',
    'notifications_tasks': 'Notifications & Tasks',
    'write_task': 'Write a task...',
    'send': 'Send',
    'no_notifications': 'No notifications',
    'perm_VIEW_DASHBOARD': 'View Dashboard',
    'perm_VIEW_CLIENTS': 'View Clients',
    'perm_MANAGE_CLIENTS': 'Manage Clients',
    'perm_SEND_EMAILS': 'Send Emails',
    'perm_VIEW_PROJECTS': 'View Projects',
    'perm_MANAGE_PROJECTS': 'Manage Projects',
    'perm_DELETE_PROJECTS': 'Delete Projects',
    'perm_VIEW_REPORTS': 'View Reports',
    'perm_ADD_REPORT': 'Add Report',
    'perm_PRINT_REPORT': 'Print Report',
    'perm_SHARE_WHATSAPP': 'Share WhatsApp',
    'perm_MANAGE_REPORTS': 'Manage Reports',
    'perm_VIEW_FINANCE': 'View Finance',
    'perm_ADD_PAYMENT_ORDER': 'Add Payment Order',
    'perm_MANAGE_FINANCE': 'Manage Finance',
    'perm_VIEW_EMPLOYEES': 'View Employees',
    'perm_MANAGE_EMPLOYEES': 'Manage Employees',
    'perm_VIEW_SALARIES': 'View Salaries',
    'perm_MANAGE_CONTRACTS': 'Manage Contracts',
    'insurance_expiry': 'Insurance Expiry',
    'contract_expiry': 'Contract Expiry',
    'full_name': 'Full Name',
    'employee_docs': 'Employee Docs',
    'payroll_system': 'Payroll System',
    'payroll_msg': 'Payroll system under development...',
    'loans': 'Loans',
    'id_residence': 'ID/Residence',
    'job_code': 'Job Code',
    'permissions_count': 'Permissions Count',
    'permission': 'Permission',
    'level_admin': 'Top Management (Admin)',
    'level_manager': 'Company Manager',
    'level_employee': 'Employee',
    'edit_company_data': 'Edit Company Data',
    'full_name_company': 'Company Full Name',
    'commercial_register': 'Commercial Register',
    'tax_number': 'Tax Number',
    'company_phone': 'Company Phone',
    'po_box': 'P.O. Box',
    'address': 'Address',
    'save_changes': 'Save Changes',
    'daily_work_report': 'Daily Work Report',
    'item_work': 'Work Item',
    'progress_percent': 'Progress %',
    'notes': 'Notes',
    'general_notes': 'General Notes',
    'new_report': 'New Report',
    'select': 'Select',
    'items_count': 'Items',
    'collected_amount': 'Collected',
    'remaining_amount': 'Remaining',
    'collection_rate': 'Collection Rate',
    'payment_name': 'Payment Name',
    'due_date': 'Due Date',
    'confirm_delete_client': 'Are you sure you want to delete client',
    'confirm_delete_employee': 'Are you sure you want to delete employee',
    'fill_client_name_phone': 'Please fill client name and phone',
    'edit_client_data': 'Edit Client Data',
    'total_contracts_value': 'Total Contracts',
    'collection_followup': 'Collection Followup',
    'ai_analysis': 'AI Analysis',
    'no_clients': 'No clients registered',
    'fill_required': 'Please fill required fields',
    'fill_basic_fields': 'Please fill basic fields',
    'password_mismatch': 'Passwords do not match',
    'password_changed': 'Password changed successfully',
    'incorrect_current_password': 'Incorrect current password',
    'change_password': 'Change Password',
    'current_password': 'Current Password',
    'new_password': 'New Password',
    'confirm_password': 'Confirm Password',
    'recent_notifications': 'Recent Notifications',
    'assigned_company': 'Assigned Company',
    'days': 'days',
    'invoices_management': 'Invoices Management',
    'invoice_date': 'Invoice Date',
    'offer_code': 'Offer Code',
    'grand_total': 'Grand Total',
    'offer_notes_placeholder': 'Terms and conditions...',
    'create_offer': 'Create Price Offer',
    'none': 'None',
    'valid_until': 'Valid Until',
    'item_description': 'Description',
    'unit': 'Unit',
    'quantity': 'Quantity',
    'unit_price': 'Unit Price',
    'select_client': 'Select Client',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    return (localStorage.getItem('eb_lang') as Language) || 'ar';
  });

  const t = (key: string) => {
    // @ts-ignore
    return translations[language][key] || key;
  };

  const dir = language === 'ar' ? 'rtl' : 'ltr';

  useEffect(() => {
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
    localStorage.setItem('eb_lang', language);
  }, [language, dir]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
